name: instagram_reels_clone
description: A Flutter client for Instagram Reels API
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: 
  image_picker: 
  video_player: 
  provider: 
  shared_preferences: 
  flutter_staggered_grid_view: 
  cached_network_image: 
  intl: 
  permission_handler: 
flutter:
  uses-material-design: true